import type { Metadata } from "next";
import "./globals.css";
// import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

// const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans")}>
      <body className="min-h-full">
        <main className="bg-blue-500 max-w-3xl mx-auto flex flex-col min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
