import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const firaCode = localFont({
  src: "../../public/Fira_Code/FiraCode-VariableFont_wght.ttf",
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", firaCode.variable)}
    >
      <body className="min-h-full">
        <main className="bg-blue-500 max-w-3xl mx-auto flex flex-col min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
